In [4]:
import numpy as np
X = np.random.normal(loc=1, scale=10, size=(1000, 50))


In [7]:
print (X)

[[ -9.55266604   3.19714867  -2.42172884 ..., -14.65035482  -2.31979936
    3.29613785]
 [ -8.11240572  -4.9294572   21.31546805 ...,   1.49962428 -14.5364543
   -4.60054046]
 [ -4.43471153   8.65586716  -3.78409131 ...,  16.54809029 -14.71760211
   10.44444852]
 ..., 
 [ 11.58911369  12.72112515   8.06640112 ...,   5.82583624   3.07168807
    3.13004944]
 [  6.05184758  -1.55749583  16.96995547 ...,  -1.11964173  -9.56525209
   14.08575467]
 [ -4.92074599   2.04903478  10.07895809 ...,  11.63163582 -11.46946646
    8.2945087 ]]


In [10]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print (m)

[ 1.09402375  0.82356496  0.95328342  0.60256518  0.59110372  0.7369354
  0.56405939  1.25911252  0.98812764  0.82569743  1.12267767  0.94381698
  1.36602118  0.95359895  0.86325922  0.93869952  0.62234322  1.48144119
  1.18264591  0.9380723   0.90356236  0.83953091  1.20626715  0.78856902
  0.6180859   0.3158905   0.5872845   0.69466946  0.60963176  0.64057676
  1.1190596   1.18360839  1.64927161  0.91364163  0.81024266  1.39822134
  0.40426178  0.94642806  0.97733312  0.90342116  0.89070379  0.75303906
  0.7077313   0.66165362  1.17153468  0.874002    0.97716428  1.41538783
  0.43390273  1.35805601]


In [11]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [13]:
r = np.sum(Z, axis=1)
print (np.nonzero(r > 10))

(array([1, 4, 5]),)


In [15]:
A = np.eye(3)
B = np.eye(3)
print (A)
print (B)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [21]:
AB = np.vstack((A, B))
print (AB)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Task 1

In [22]:
import pandas
data = pandas.read_csv('/home/nazarov/09-education/04 - HSE ML/task01/titanic.csv', index_col='PassengerId')

In [23]:
data[:10]

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
6                0      0            330877   8.4583   NaN        Q  
7                0      0             17463  51.8625   E46        S  
8                3      1            349909  21.0750   NaN        S  
9                0      2            347742  11.1333   NaN        S  
10               1      0            237736  30.0708   NaN        C